# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 024b672c5e31cd2d71ea6a260581716cb00a4e9749b8e055f47e80c901e77e9dbca1453e095eb388f7d7ea1f48a8feba22962ca48ab9ebbb8dc1d185c4bd9b0c

test:
  secret_key_base: 4a8f01918b1ca2eab90f16a9a559300934649b4349b66dd13762965dcc3b910fe1f05d735c0c4c34fba8aa60a389dc27307f4483ac12034e5cd283b03f735e2c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
